### ISSUE TITLE
Allows a DatacenterBroker to sort submitted VMs and Cloudlets

### ISSUE THREAD

**Issue by RaysaOliveira** [manoelcampos/cloudsim-plus#102]
# Feature
- Updates the `DatacenterBroker` interface and implementing classes, including the methods `setVmComparator` and `setCloudletComparator` to enable a developer to set a `Comparator` object (which can be given as a Lambda Expression) to be used to sort `Vms` and `Cloudlets`, respectively, every time when such objects are submitted to the broker.
This new feature ensures that such submitted objects are are sorted before requesting their creation.
- This sorting feature enables defining priorities to request the creation of `Vms` and `Cloudlets`, following the order defined by the given `Comparators`.
- If no `Comparator` is set, the broker will request the creation of the submitted objects in the order they were submitted.

# Notes
The feature was introduced in the previous commit d2c223d53c5445f84a3236ecd443ecd603b94e79. This issue is just for documentation purposes.

**Comment by manoelcampos** [comment]
Closed by d2c223d53c5445f84a3236ecd443ecd603b94e79
