### ISSUE TITLE
Some Cloudlets don't finish when using the CompletelyFairScheduler and a Workload file

### ISSUE THREAD

**Issue by RaysaOliveira** [manoelcampos/cloudsim-plus#114]
When using the `WorkloadFileReader` class to read a workload file to create Cloudlets, such as the "METACENTRUM-2009-2.swf" file, some Cloudlets are not finished and no error message is shown.

## Expected behavior
All submitted Cloudlets which should be executed or error messages should be presented for those ones which couldn't.

## Actual behavior 
Some cloudlets are not finished and no error message is shown.

## If it is a more wide problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
As an example, load the METACENTRUM-2009-2.swf using the `WorkloadFileReader` class and limit the number of cloudlets to be created to 50. Create 30 VMs with PEs and MIPS between:
VM_PES = {2, 4, 6}
VM_MIPS = {1000, 1500, 2500}

In this case, only 41 cloudlets are finished.

## Specifications like the version of the project, operating system or workload file used
CloudSim Plus 1.2.4

**Comment by manoelcampos** [comment]
This issue could not be reproduced anymore. Probably, the changes in #153 and #163 already fixed this one. Check the commit messages there for details.
