### ISSUE TITLE
Cloudlet predicted file transfer time and SanStorage network latency

### ISSUE THREAD

**Issue by AbderrahmanL** [manoelcampos/cloudsim-plus#132]
## Expected behavior:
 To include network latency when calculating transfer time in the case of SanStorage

## Actual behavior :
Not including the latency

## Suggestion
Instead of making two methods to get transfer time in both SanStorage and HarddriveStorage (getFileTransferTimePlusNetworkLatency for SanStorage and getTransferTime for HarddriveStorage), making one for HarddriveStorage, and then redefining It In the SanStorage class to take network latency in consideration will make It possible to use that one method directly on FileStorage objects in the predictFileTransferTime method of DatacenterSimple instead of writing new code for that.

**Comment by manoelcampos** [comment]
Hello @AbderrahmanL,

Are you working on this issue? Please let me know.
I've just fixed a critical issue (#135). So I suggest you update your fork, mainly if you are working on the issue you reported.

**Comment by AbderrahmanL** [comment]
Hello @manoelcampos 
I'll work on fixing It its just that Im new to contribution Using github been in the microsoft eco systeme for a while so I'll read the contribution guide and follow the guidelines the best i can

**Comment by manoelcampos** [comment]
Ok. Thanks for that.
