### ISSUE TITLE
Wondering if Cloudsim-plus could simulate package-level network application

### ISSUE THREAD

**Issue by jlxcsong** [manoelcampos/cloudsim-plus#139]
Sorry to bother you, I'm new to Cloudsim-plus.
After several days' debugging about NetworkVmExamples, I am still confused the way to simulate a package-level network application/protocol with Cloudsim-plus. For Example，heartbeat protocol or three-way handshake.
However, CloudSim is supportable for message-passing applications. As a typical fork of CloudSim, it may be also supportable for Cloudsim plus but I haven' noticed that. 
here is my question:
Q1: I'm wondering if Cloudsim-plus could simulate package-level network application.
Q2: I believe cloudsim-plus is able to simulate communications between hosts or vms，could you give me a reference or example?
Thanks for your kindly reply.

**Comment by manoelcampos** [comment]
Please subscribe to the forum to get support.
I try to answer all questions if users read the forum policy and show they are doing their homework.

**Comment by jlxcsong** [comment]
Sorry, thank you for your advice.
