### ISSUE TITLE
Power consumption inconsistency

### ISSUE THREAD

**Issue by alexandredias3d** [manoelcampos/cloudsim-plus#153]
## Expected behavior
Power consumption should be the same, or at least very close, even when changing the scheduling interval.

## Actual behavior 
Power consumption is varying way too much for some values of scheduling interval.

## If it is a more wide problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
Here is a modified version of PowerExample to show this issue. SCHEDULING_INTERVAL is now an array, and will execute one simulation for each value in it. Here is a link to the code:
https://gist.github.com/alexandredias3d/52564a74f6c5d7df7cb6448614868463

**Comment by manoelcampos** [comment]
Hello @alexandredias3d 

Could you please try the new version available at the dev branch with the new PowerExampleSchedulingInterval example and give me some feedback?

Thanks for your contributions.

**Comment by manoelcampos** [comment]
Hello @alexandredias3d 

Could you please try the new version available at the dev branch with the new PowerExampleSchedulingInterval example and give me some feedback?

Thanks for your contributions.

**Comment by manoelcampos** [comment]
You can check the messages in the last 2 commits and the new comments in the code for more details.

**Comment by manoelcampos** [comment]
Btw, realize that the way the power consumption is computed in a different way now.
But it gives you new possibilities. Check the `Host.getUtilizationHistory()` documentation for new details.

**Comment by alexandredias3d** [comment]
Hi @manoelcampos,

Sorry for the late reply. I have tested out the new features and they are working perfectly. I believe that using the DoubleSummaryStatistics from the UtilizationHistory will ease a lot the development of new heuristics for VM consolidation.

Thanks for your hard work.

**Comment by manoelcampos** [comment]
Don't worry. And great that it's working as expected.
Could you please mark the discussion at google groups as completed?
Thanks.
