### ISSUE TITLE
The method getUniqueTaskId of class TaskData can not guarantee the task(cloudlet) id is unique

### ISSUE THREAD

**Issue by RobertLexis** [manoelcampos/cloudsim-plus#159]
## Expected behavior
The method `getUniqueTaskId` of class `TaskData` should guarantee that the cloudlet id is unique.
## Actual behavior 
The implementation of `getUniqueTaskId` follows:
```
long getUniqueTaskId(){
    return getJobId() + getTaskIndex();
}
```
When jobId = 1, taskIndex = 1, the cloudlet id will be 2; while jobId = 2, taskIndex = 0, another cloudlet with id 2 will be created.

I found this bug when running the example of GoogleTaskEventsExample1. The provided trace task_events_sample_1.csv has two tasks (jobId:1, taskIndex 1; jobId:2, taskIndex 0). In this case, two cloudlet with id 2 will be created.
You can also verify the existence of this bug by running the GoogleTaskEventsExample1 and counting the number of cloudlets. According to the trace file, the number of cloudlets is expected to be 10, but as you will see in the console, only 7 cloudlets is 'created'. This is because there are 3 cloudlets is shadowed.
## Specifications like the version of the project, operating system or workload file used
+ MacOs 10.13.6
+ cloudsimplus version 4.0.5
+ workload file task_events_sample_1

**Comment by manoelcampos** [comment]
Thanks for reporting.
The approach I used to avoid this issue was to concatenate, instead of adding, JobID and TaskId.
But I don't know if it will cause overflow when we have large values for those fields.
I need to perform some tests to check that.
