### ISSUE TITLE
Some cloudlets don't finish execution: some are INEXEC state, other are in QUEUE state.

### ISSUE THREAD

**Issue by codesonteen** [manoelcampos/cloudsim-plus#163]
In my simulation scenario, I generated random amount of cloudlets every second. In each single second, the submission delay for each individual cloudlet was set by second+randomMillisecond.
The Cloudlets mips length were configured to 100 mips.
The VMs PE were configured to 10000 mips per PE
Execution of some Cloudlets is not finished. Some are queueing, some are in execution.
This case happens when I used CloudletSchedulerSpacedShare and CloudletSchedulerCompletelyShared

## Expected behavior
Every Cloudlet created and submitted must be successfully executed.

## Actual behavior 
Some cloudlets are not finished. Some of them are in execution, Some of them are still in queue.
https://gist.github.com/codesonteen/7bd785b740ca050136c9c8d182318104

## If it is a more wide problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
- Issue happens using CloudletSchedulerSpaceShared and CloudletSchedulerCompletelyShared
- Simulation File => https://gist.github.com/codesonteen/c45e97d7840826a8dcdb464e51fddad2
- Result => https://gist.github.com/codesonteen/7bd785b740ca050136c9c8d182318104

## Specifications like the version of the project, operating system or workload file used
- Java 10
- macOS Mojave
- CloudSim Plus 4.0.4

**Comment by manoelcampos** [comment]
Could you try to reproduce the issue with the minumum number of cloudlets and without random numbers? It's difficult to identify the source of the issue when random numbers are used.
Please also update to the latest 4.0.6 version and try the example with that version.

Thanks for reporting.

**Comment by codesonteen** [comment]
I reproduce the scenario with static 60 cloudlets arrival per second.
Each single cloudlets submission delay are secondCount + randomMilliseconds.

The method for generate random milliseconds
```
public double getRandomMilliseconds() {
    java.util.Random random = new java.util.Random();
    double rangeMin = 0.0;
    double rangeMax = 0.9;
    return rangeMin + (rangeMax - rangeMin) * random.nextDouble();
}
```

The above method return a very long decimal point.
```
0.4079729639119738
```

I changed the return value by applying DecimalFormat("####.##"), Math.ceil and Double.parseDouble
```
return Double.parseDouble(new DecimalFormat("####.##").format(rangeMin + (rangeMax - rangeMin) * random.nextDouble()));
```

After I changed, the return value will be look like below
```
0.41
```

And I had run the simulation and there is no more "INEXEC" and "QUEUE" state.

According to the test I have run, It's seem to be an issue on processing too long decimal point instead of real numbers.

**Comment by codesonteen** [comment]
After I ran for several times, The issue is back.

Code: https://gist.github.com/codesonteen/1b3251045f274604a560528f21017db5
Result: https://gist.github.com/codesonteen/a1898d203a17696d571170c1a8bdc0b2

**Comment by manoelcampos** [comment]
I'll check that and let you know. And thanks for the tips.

**Comment by manoelcampos** [comment]
If you change the first line inside the constructor to `Log.setLevel(ch.qos.logback.classic.Level.WARN);`, the messages will be filtered and you'll see more easily the warning 
`WARN  60.98: DatacenterSimple: Vm 0/Broker 2 destroyed on Host 0/DC 1. It had a total of 1794 cloudlets (running + waiting).`.

Now I have to figure out the source of the issue.

**Comment by manoelcampos** [comment]
I've streamlined your example to reproduce the issue with fewer Cloudlets. It uses a static seed for the random number generator. This way, we can get the same results all the time we run the code.
If you wanna try, update your fork and download the example [here](https://gist.github.com/manoelcampos/535ce534c206fe50b94a5a475858fc20).

**Comment by manoelcampos** [comment]
Hello @codesonteen,

Your tip about the small delay values is correct. Check the comment at the top of the example I provided above and how to fix the issue. In this case, it's just a configuration.

So, I'm thinking of just changing the warning I shown 2 messages above to make it clear that the `minTimeBetweenEvents` should be reduced in such cases.

**Comment by manoelcampos** [comment]
I just added that example to the examples module to show this is just a configuration issue and how to fix it if it happens in your simulations.

The new example is available at the master branch at [MinTimeBetweenEventsExample.java](https://github.com/manoelcampos/cloudsim-plus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/MinTimeBetweenEventsExample.java)

**Comment by codesonteen** [comment]
**Thank you very much for your hard working.**

I tried your new [MinTimeBetweenEventsExample.java](https://github.com/manoelcampos/cloudsim-plus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/MinTimeBetweenEventsExample.java), Change the constant `MIN_TIME_BETWEEN_EVENTS` from 0.1 to 0.01 and It's work.

I'll implement to my simulation scenario further. And If I face any issue, I'll let you know.

**Comment by manoelcampos** [comment]
Great!
