### ISSUE TITLE
Confusion between energy, power and their units

### ISSUE THREAD

**Issue by humaira-salam** [manoelcampos/cloudsim-plus#178]
Following was _Originally posted by @manoelcampos in https://github.com/manoelcampos/cloudsim-plus/pull/129#issuecomment-384314909_

---------------------------------------------------------------------------

> There was just a confusion between energy and power.
> In fact, everywhere you find a variable `double power` it means energy.
> 
> Power can be measured in watts while energy consumption can be measured in watt-second (not Watt/second), which is the same as 1 joule/second. However, most users may not be familiar with the joule/second unit. 
> 
> This way, I think it's more intuitive to use watt-second (Ws) for the `getPower()` and 
> Kilowatt-hour (kWh) for the `getPowerInKWattsHour()`.
> 
> Since you just performed small changes in the documentation, I preferred to fix such units everywhere myself. 
> 
> Check the last 3 commits. Thanks again for contributing.

---------------------------------------------------------------------------

I don't agree that 1 Watt-Second is the same as 1 Joule/Second. Joule is the unit of energy and it is same as Watt-Second (See [here](https://en.wikipedia.org/wiki/Joule#Watt_second)). That is,

Watt = Joule / Second

or 

Joule = Watt*Second

Now, this raises a confusion in the [PowerExample](https://github.com/manoelcampos/cloudsim-plus/blob/79d97034954686aa3b44179c3b6a067ea426a880/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/power/PowerExample.java#L256) where Watt-Seconds are again multiplied by a quantity in Seconds. 

Also, when I look at [PowerModelSimple](https://github.com/manoelcampos/cloudsim-plus/blob/080afa04e49beffc8b00ef56e1675d6eb9c40e08/cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/models/PowerModelSimple.java#L49), the maxPower parameter should restrict maximum power consumption (watts) and not maximum energy consumption (Watt-Second). Therefore, the `getPower()` function should return Watts, and then multiplying it with time-intervals would give us the consumed energy.

**Comment by manoelcampos** [comment]
Thanks for your contribution @humaira-salam 

> I don't agree that 1 Watt-Second is the same as 1 Joule/Second. Joule is the unit of energy and it is same as Watt-Second.

> Also, when I look at [PowerModelSimple], the maxPower parameter should restrict maximum power consumption (watts) and not maximum energy consumption (Watt-Second). Therefore, the `getPower()` function should return Watts, and then multiplying it with time-intervals would give us the consumed energy.

You're right. Watt-sec is not Joule/Second, but Watt.
I changed the documentation for methods in the following classes and interfaces: 

- PowerAware
- PowerModel
- PowerModelSimple

The PowerModel.getEnergyLinearInterpolation() is correctly returning Watts-sec because there the time parameter. The DatacenterPowerSupply.getPower() is returning the energy consumption for the entire simulation time in Watts-sec (despite the name of the method may be confusing).

> Now, this raises a confusion in the PowerExample where Watt-Seconds are again multiplied by a quantity in Seconds.

I renamed some variables in PowerExample and PowerExampleSchedulingInterval.

However, due to this confusion, the PowerAware.getPowerInKWattsHour() is not correct. It should be getPowerInKWatts() and therefore, the conversion is just watts/1000.

Could you please take a look at the [last commit in dev branch](https://github.com/manoelcampos/cloudsim-plus/commit/fa4856df0a43750dea1b623d23e5f1bdb2baee10)?

**Comment by humaira-salam** [comment]
@manoelcampos , thanks for your response. Sorry, I am little busy these days but I will surely look in to the changes and will get back to you in few days.

**Comment by manoelcampos** [comment]
Don't worry. I appreciate any help. Just take your time.
Thanks.

**Comment by manoelcampos** [comment]
Hello @humaira-salam,

I've been working on several other issues in parallel and it was becoming quite difficult to manage all of them. This way, I had to close this issue.
If you take a look at the commit 18efb059be03ff8227ea5a4a0ad2a8e110bbce09 and find something that I may have missed, I'll be happy to fix.

Thanks again.

**Comment by humaira-salam** [comment]
Hello @manoelcampos,

Thanks for all the changes, I agree with them. However, in [PowerExample](https://github.com/manoelcampos/cloudsim-plus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/power/PowerExample.java) (line [260](https://github.com/manoelcampos/cloudsim-plus/blob/9213a8760cc8ad001477feec0b54cdea6aea7237/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/power/PowerExample.java#L260) and [266](https://github.com/manoelcampos/cloudsim-plus/blob/9213a8760cc8ad001477feec0b54cdea6aea7237/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/power/PowerExample.java#L266)) the variable `prevWattsPerInterval` should be renamed to `prevWattsSec` for consistency.

**Comment by manoelcampos** [comment]
Thanks again.
Just fixed that in PowerExample and PowerExampleSchedulingInterval.
I'm going to update the repo soon.
