### ISSUE TITLE
Host's start up and shutdown time are not being updated correctly

### ISSUE THREAD

**Issue by manoelcampos** [manoelcampos/cloudsim-plus#181]
After fixing issue #128, Hosts can be activated and shut down according to demand.
However, the start up and shut down time are not being correctly updated.

## Expected behavior
Every time a Host startup or shuts down, the respective attributes must be updated.
A totalUpTime attribute should be introduced to store the total time that the Host stayed active along the simulation execution.

## Actual behavior 
The attributes are updated only for the first startup and shutdown.

## Specifications like the version of the project, operating system or workload file used
CloudSim Plus 4.3.0

**Comment by neha161** [comment]
How much time is needed for host startup?

**Comment by manoelcampos** [comment]
The feature you mentioned is a work in progress. Check PR #311

**Comment by neha161** [comment]
Can you suggest me in general how much time is needed for host startup.

**Comment by manoelcampos** [comment]
This is completely variable. Depends on the OS type (Windows, Linux, etc), number of startup process, hardware and so on. Therefore, there is no such a thing as "suggested startup time".

**Comment by neha161** [comment]
Thanks for the clarification.

**Comment by manoelcampos** [comment]
Hello @neha161 
Check the new v6.4.0 that has just been released.
It closes issue #281, introducing support to hosts startup and shutdown delays.
There is a link to a complete example in the issue link above.

**Comment by neha161** [comment]
Thanks for the update

**Comment by manoelcampos** [comment]
You're welcome. Please take a second to give CloudSim Plus a star, we appreciate that.
