### ISSUE TITLE
Deallocating a vm from a host does not bring back the hosts resources. Vm takes all resources even if it is destroyed

### ISSUE THREAD

**Issue by ShyamSundarVijayakumar** [manoelcampos/cloudsim-plus#196]
## Actual behaviour

Vm takes all the resources it has when it is destroyed or deallocated.
This behaviour is same even with the latest version CloudSim Plus 4.3.5

## Expected behaviour

When a vm is deallocated from a host,the host should get back all the resources that vm was using so that it can allocate them to the vms which arrive after that.

**Comment by ShyamSundarVijayakumar** [comment]
Scenario: When a vm finishes cloudlet execution it's resources are deallocated and after some time the vm is allocated again.
Actual behaviour:   Vm takes all the resources it has when it is destroyed or deallocated.
methods used:        host.getRamProvisioner().deallocateResourceForVm(vm);
				host.getBwProvisioner().deallocateResourceForVm(vm);
				host.getVmScheduler().deallocatePesFromVm(vm);
(or)                      vm.deallocateResource(Processor.class);
				vm.deallocateResource(Ram.class);
(or) Host.destroy(vm)
This behaviour is same even with the latest version CloudSim Plus 4.3.5 
 
Expected behaviour: When a vm is deallocated from a host,the host should get back all the resources that vm was using so that it can allocate them to the vms which arrive after that.

**Comment by manoelcampos** [comment]
Hello @ShyamSundarVijayakumar,

Please follow the ISSUE template that appears to you when you create the issue and place all the information into a single comment, deleting this 2nd comment. 

Thanks for collaborating.

**Comment by manoelcampos** [comment]
Could you please provide a minimum simulation scenario (based on the BasicFirstExample) that reproduces the issue?

**Comment by ShyamSundarVijayakumar** [comment]
Hi,
I have created a simulation scenario using CreateCloudletafterlastOneFinishes example.
[CreateCloudletafterlastOneFinishes.txt](https://github.com/manoelcampos/cloudsim-plus/files/3146147/CreateCloudletafterlastOneFinishes.txt).

In the file i have mentioned the methods which did not deallocate.And also there are methods like,
host.getRamProvisioner().deallocateResourceForVm(Vm);
host.getBwProvisioner().deallocateResourceForVm(Vm);
host.getVmScheduler().deallocatePesFromVm(Vm);
which deallocates with some error in console .
Error in log looks like,
[main] INFO DatacenterBroker - 10.1: DatacenterBrokerSimple2: Cloudlet 0 finished and returned to broker.
[main] INFO CloudSim - NaN: Processing last events before simulation shutdown.
[main] INFO DatacenterBroker - NaN: DatacenterBrokerSimple2 is shutting down...
[main] INFO DatacenterBroker - NaN: DatacenterBrokerSimple2: Requesting Vm 0 destruction.
[main] INFO DatacenterSimple - NaN: DatacenterSimple: Vm 0/Broker 2 destroyed on Host 0/DC 1. 
[main] INFO CloudSim - Simulation: No more future events

[main] INFO CloudInformationService - CloudInformationService0: Notify all CloudSim Plus entities to shutdown.

[main] INFO DatacenterSimple - NaN: DatacenterSimple1 is shutting down...
[main] INFO CloudSim - 
================== Simulation finished at time NaN ================== 

In the other simulation scenarios,when i submit multiple vms at the start and try to deallocate after each vm finishes, it deallocates the vm that finished first but simulation ends there.Other vms status does not showup.
Could you suggest any ways to resolve this error.
I have tried alternative ways for example, I created an additional datacenter with a host and tried to migrate the vm to this DC's host once vm finishes executing in initial DC. Vm is submitted to the other datacenter broker after it finishes in the initial one .This way it created a copy of the same vm in the other datacenter.So now i have to destroy the old copy vm in the initial DC and i destroy it. With this way the NAN error in log disappears and the simulation runs fine,but even though the vm is destroyed or deallocated in the initial DC, the used resources does not get freed in host.(i.e in this case vm still has host resources). Note: In host's vmlist the vm which is destroyed disappears.
Thanks in advance.

**Comment by manoelcampos** [comment]
Hello @ShyamSundarVijayakumar 

I checked your example and realized you are manually trying to deallocate resources used by a VM, when a specific Cloudlet finishes. Despite you can call the deallocateResourceForVm methods, you're not supposed to do that. VM resources should be deallocated only when a Host requests the VM destruction, by calling host.destroyVm. Some methods such as the deallocateResourceForVm are only publically available because some design issues that I won't be tackling on the short or medium term.

If you want to destroy the VM, you have to call the method I mentioned. If you want the VM to be destroyed automatically after becoming idle, check the DynamicVmsArrival example that uses the DatacenterBroker's setVmDestructionDelay method.

**Comment by manoelcampos** [comment]
If you have any questions, please subscribe to the forum and provide all the information required to join. And please don't forget to give CloudSim Plus a star, it helps to promote the project and keep it going.
