### ISSUE TITLE
Errors in throttled load balancer code in cloudanalyst

### ISSUE THREAD

**Issue by naadi883** [manoelcampos/cloudsim-plus#213]
Errors in throttled load balancer code in cloudanalyst
I am using cloudanalyst to perform some modifications to the load-balancer called throttled load-balancer, but I have some problems with the original code.

I am trying to change the number of VMs to see how it distributes tasks between them but it always gives me the same result for only 4 VMs whatever the number I entered.

This error only happens with throttled load-balancer but it works correctly in round robin and active monitoring.

I really appreciate if any one could help me to solve this problem. I am waiting for your answers, Thanks in advance.

**Comment by manoelcampos** [comment]
Hello @naadi883 
Sorry but CloudSim Plus has nothing to do with CloudAnalyst.
CloudAnalyst is one more abandoned project based on CloudSim.

**Comment by naadi883** [comment]
Hello @manoelcampos 
Thank you for your answer but could you plz suggest me some one who can help me in this problem? It is very important for me and i could not find neither the reason for this problem nor some one who can help me.
thank you

**Comment by naadi883** [comment]
And if i use the cloudsim plus, can i add new loadbalancer for cloudlets?

**Comment by manoelcampos** [comment]
The DatacenterBroker is the one accountable to define how Cloudlets are mapped to VMs.
There are different implementations available at the `org.cloudbus.cloudsim.brokers` package and you can implement your own policy. There are some classes that extend DatacenterBrokerSimple which may be used to understand how to implement your own policy.

If you have any further questions, please subscribe to the forum.

**Comment by naadi883** [comment]
I saw the package org.cloudbus.cloudsim.brokers
so could you please help me to change this file to run by using cloudsim plus
[Throttled load balancing.docx](https://github.com/manoelcampos/cloudsim-plus/files/3373520/Throttled.load.balancing.docx)
 package cloudsim.ext.datacenter;

import java.util.Iterator;
import java.util.Map;

import cloudsim.ext.Constants;
import cloudsim.ext.event.CloudSimEvent;
import cloudsim.ext.event.CloudSimEventListener;
import cloudsim.ext.event.CloudSimEvents;

/**
 * This class implements {@link VmLoadBalancer} as a Throttled load balancer. Each VM is
 * allocated only one task at a time and can be allocated another task only when the current
 * task has completed. The ThrottledVmLoadBalancer does not implement any task queueing 
 * functionality, but returns a valid VM id in the <code>getNextAvailableVm</code>
 * only if available. The calling {@link DatacenterController} should implement the task 
 * queueing locally.
 * 
 * The ThrottledVmLoadBalancer implements CloudSimEventListener to get notified of the VM's
 * being allocated and freed up by the {@link DatacenterController}
 * 
 * @author Bhathiya Wickremasinghe
 *
 */
public class ThrottledVmLoadBalancer extends VmLoadBalancer implements CloudSimEventListener {
	
	private Map<Integer, VirtualMachineState> vmStatesList;
	
	/** 
	 * Constructor
	 * 
	 * @param dcb The {@link DatacenterController} using the load balancer.
	 */
	public ThrottledVmLoadBalancer(DatacenterController dcb){
		dcb.addCloudSimEventListener(this);
		this.vmStatesList = dcb.getVmStatesList();
		//dcb.addCloudSimEventListener(this);
	}

	/**
	 * @return VM id of the first available VM from the vmStatesList in the calling
	 * 			{@link DatacenterController}
	 */
	@Override
	public int getNextAvailableVm(){
		int vmId = -1;
		
		if (vmStatesList.size() > 0){
			int temp;
			for (Iterator<Integer> itr = vmStatesList.keySet().iterator(); itr.hasNext();){
				temp = itr.next();
				VirtualMachineState state = vmStatesList.get(temp); //
				//System.out.println(temp + " state is " + state + " total vms " + vmStatesList.size());
				if (state.equals(VirtualMachineState.AVAILABLE)){
					vmId = temp;
					break;
				}
			}
		}
		
		allocatedVm(vmId);
		
		return vmId;
		
	}
	
	public void cloudSimEventFired(CloudSimEvent e) {
		if (e.getId() == CloudSimEvents.EVENT_CLOUDLET_ALLOCATED_TO_VM){
			int vmId = (Integer) e.getParameter(Constants.PARAM_VM_ID);
			vmStatesList.put(vmId, VirtualMachineState.BUSY);
			System.out.println(vmId);
		} else if (e.getId() == CloudSimEvents.EVENT_VM_FINISHED_CLOUDLET){
			int vmId = (Integer) e.getParameter(Constants.PARAM_VM_ID);
			vmStatesList.put(vmId, VirtualMachineState.AVAILABLE);
			System.out.println(vmId);
		}
	}
	

}

**Comment by naadi883** [comment]
please help me

**Comment by naadi883** [comment]
could you pls give me some hints to how it works?
pls let me learn from you
thanks in advance

**Comment by naadi883** [comment]
HI
please i want to ask you about running Example 1 in your cloudsim plus why it doent give results?
and this message comes "editor doesnt contain main type"
thanks in advance

**Comment by naadi883** [comment]
HI
please i want to ask you about running Example 1 in your cloudsim plus why
it doent give results?
and this message comes "editor doesnt contain main type"
thank you in advance
