### ISSUE TITLE
Example running problems

### ISSUE THREAD

**Issue by Krazymud** [manoelcampos/cloudsim-plus#227]
Hello! I am new to Cloudsim plus, when I run the MinTimeBetweenEventsExample.java, the results look a little weird:

![1](https://user-images.githubusercontent.com/22273043/74342919-375e5500-4de5-11ea-91b0-0c877b0fed0f.png)

When I turn the MIN_TIME_BETWEEN_EVENTS to 0.01, the result:

![2](https://user-images.githubusercontent.com/22273043/74343014-59f06e00-4de5-11ea-9b86-179b965728c6.png)

Those ExecTime Seconds look weird...

**Comment by manoelcampos** [comment]
Hello @Krazymud 

Thanks for reporting. The issue was just in the format to print the results.
Check the message of commit 9f13b06 for details.
I took the change to refactor the example and update the documentation.
