### ISSUE TITLE
Wrong resource allocation on dynamic resource utilization during VM migration

### ISSUE THREAD

**Issue by ehsankhodayar** [manoelcampos/cloudsim-plus#250]
The main problem is that when you use a dynamic resource utilization model for one of the VM resources such as MIPS, the resource allocation method in the HostSimple class makes a wrong resource allocation for the VM in the migration process. 

As a short example, consider a VM with 4 PEs and MIPS capacity 2000 for each PE. Assume the VM is going to have a dynamic MIPS utilization during its execution time. Now let consider at time t+ which the VM's MIPS utilization is 250 and the VM is chosen for migrating out to another destination host. In the resource allocation method of HostSimple class in destination hosts, it will be first checked that the requested VM is created or not. If the VM is not created, it considers the total capacity for each resource of the requested VM, such as MIPS. 

But when we diagnose a VM as a created one, such as a VM during the migration process, it just considers the requested amount of capacity at that time such as 250 MIPS for the mentioned VM and that VM is not able to achieve its default MIPS capacity (2000 MIPS) during its execution time anymore. 

In my simulation, I solved the problem temporarily by making the requested VM for migrating out as a not created VM, then make it as a created VM after the resources at the target host are allocated to the requested VM. In other words, If you implement a migration scenario with a full utilization model for all resources, this problem will never occur. 

There are also other few bugs that are not related to this topic and I will bring them up in a new topic in the future.

**Comment by manoelcampos** [comment]
The [MigrationExample1](https://github.com/manoelcampos/cloudsim-plus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/migration/MigrationExample1.java) uses a `UtilizationModelDynamic` for CPU. Maybe the issue was fixed after #247.

Please try thew new version and let me know how it goes.

**Comment by ehsankhodayar** [comment]
The dynamic model in this example is only applied on the last cloudlet. But I test it with a lower maximum utilization threshold during the cloudlet creation and it was fine and the problem was fixed. Thanks for the new updates.

**Comment by manoelcampos** [comment]
Then, may I close the issue?

**Comment by ehsankhodayar** [comment]
Yes, you can. 

Thanks a lot

**Comment by manoelcampos** [comment]
Issue fixed by PR #248.
Thanks for reporting.
