### ISSUE TITLE
Comparison Page Out Of Date

### ISSUE THREAD

**Issue by agent00jackson** [manoelcampos/cloudsim-plus#262]
I was looking at this comparison page and the gists used to show the comparison are no longer available:
https://github.com/manoelcampos/cloudsim-plus/blob/master/docs/CloudSim-and-CloudSimPlus-Comparison.html

**Comment by manoelcampos** [comment]
Hello @agent00jackson 
Thanks for reporting.
In fact, I deleted those gists by mistake, thinking they were just some random examples.
I contacted GitHub to restore them, but it's only possible in a 90-days time frame and those gists were deleted long ago.

Unfortunatelly, I won't be able to recreated them in the short term.

**Comment by manoelcampos** [comment]
Hey @agent00jackson 
I've just recreated the examples. They are even better documented.
Check the same link again.
