### ISSUE TITLE
how to convert csv (GCT) workflow to SWF file

### ISSUE THREAD

**Issue by maahhi** [manoelcampos/cloudsim-plus#270]
Hi
I want to convert GCT files to SWF.
I read the "GoogleTaskEventsExample1.java," and I understood how to load CSV files in a Cloudsim object. Is there any way to export the SWF file from this object? or do you have a better solution for my issue?

**Comment by manoelcampos** [comment]
For questions, please subscribe to the group or use the discussion tab.
