### ISSUE TITLE
How can I build cloudsim-plus on my host?

### ISSUE THREAD

**Issue by jerry-yuan** [manoelcampos/cloudsim-plus#275]
I am building an simulate app with cloudsim-plus ,spring boot and py4j-server. I found that the configuration of logback inside the cloudsim-plus has overrided the configuration from spring boot. As the result, I decided to build it myself. But if I use the jars built by myself, I got an ClassNotFoundException, while it will not throw ClassNotFoundException when I change the dependency to jars from maven repository. I wan't to know how to build this project.

# WHEN REPORTING AN ISSUE:

## Actual behavior 
If I try to new CloudSim(),there will be ClassNotFoundException in other project.
## Expected behavior
I can refercence the org.cloudbus.cloudsim.core.CloudSim and there will not be ClassNotFoundException

## If it is a wider problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
1.change the version of cloudsim-plus (in cloudsim-plus/pom.xml)
2.build cloudsim-plus by:
```
# if I try not to skip tests there will be some errors like InvalidPath
$ mvn install -Dmaven.test.skip=true
```
3.Create a plain new java project and reference the jars that installed to local repository:
```
<dependency>
            <groupId>org.cloudsimplus</groupId>
            <artifactId>cloudsim-plus</artifactId>
            <version>6.0.0.my.version</version>
</dependency>
```
4.Create a main method and try to instance a CloudSim object and it will throw a ClassNotFoundException
(Event though class CloudSim can be found in IDEA)
## Specifications like the version of the project, operating system or workload file used
I checked out the latest version of cloudsim-plus and build it.
I am using Windows 10.

**Comment by jerry-yuan** [comment]
I tried to remove these from pom.xml and it works:
```xml
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.0.2</version>
				<configuration>
					<archive>
						<manifest>
							<!-- Adds dependencies to classpath into the manifest file inside the jar !-->
							<addClasspath>true</addClasspath>

							<!-- Defines that the dependencies will follow the same
							 hierarchical directory structure of a maven repository !-->
							<classpathLayoutType>repository</classpathLayoutType>

							<!-- Defines the root folder where the dependencies are. In this case
							 is the the root of the local maven repository. !-->
							<classpathPrefix>${user.home}/.m2/repository/</classpathPrefix>
						</manifest>
					</archive>
				</configuration>
			</plugin>
```
and I have compared the output jar content and found there has two different files `META-INF/MANIFEST.MF` and `META-INF/maven/pom.xml` and there is the differences:
```
$ diff ./buged/META-INF/MANIFEST.MF ./normal/META-INF/MANIFEST.MF
1a2
> Archiver-Version: Plexus Archiver
3,15d3
< Class-Path: C:/Users/yuanx/.m2/repository/org/apache/commons/commons-m
<  ath3/3.6.1/commons-math3-3.6.1.jar C:/Users/yuanx/.m2/repository/org/
<  apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar C:/Users/y
<  uanx/.m2/repository/org/apache/commons/commons-collections4/4.1/commo
<  ns-collections4-4.1.jar C:/Users/yuanx/.m2/repository/com/google/code
<  /gson/gson/2.8.2/gson-2.8.2.jar C:/Users/yuanx/.m2/repository/ch/qos/
<  logback/logback-core/1.3.0-alpha4/logback-core-1.3.0-alpha4.jar C:/Us
<  ers/yuanx/.m2/repository/ch/qos/logback/logback-classic/1.3.0-alpha4/
<  logback-classic-1.3.0-alpha4.jar C:/Users/yuanx/.m2/repository/com/su
<  n/mail/javax.mail/1.6.0/javax.mail-1.6.0.jar C:/Users/yuanx/.m2/repos
<  itory/javax/activation/activation/1.1/activation-1.1.jar C:/Users/yua
<  nx/.m2/repository/org/slf4j/slf4j-api/1.8.0-beta2/slf4j-api-1.8.0-bet
<  a2.jar
```

**Comment by jerry-yuan** [comment]
Actually, I found if I remove the classpath from MANIFEST.MF (by set /build/plugins/plugin<maven-jar-plugin>/configuration/archive/manifest/addClasspath to false)  and the jar will work well. If it is possible that to remove classpath from MANIFEST.MF and what is it used for?

**Comment by manoelcampos** [comment]
The classpath is used to enable running the examples from the generated uber jar, which includes all dependencies.
If you don't want to change how CloudSim Plus is built and use the version from Maven Central (which is the recommended way), you can try creating a `resources/logback.xml` file inside your project to define your own logging configuration.
