### ISSUE TITLE
Google trace- convert percent values to the values usable by cloudlets/VMs

### ISSUE THREAD

**Issue by Znbne** [manoelcampos/cloudsim-plus#276]
I am going to implement a scenario using Google workload and CloudSim-plus. However, as you know the values for resource usage (CPU, Mem, Storage) are stated as percent in the trace. I explored the code of CloudSim-plus to figure out where and how the values are converted to MIPS and Bytes, but I did not find them. Could you please guide me in this regard?

**Comment by manoelcampos** [comment]
For questions, please use the forum or discussion tab.
