### ISSUE TITLE
OutOfMemoryError with CloudSim Plus v6 and Google Traces

### ISSUE THREAD

**Issue by Doaa-h** [manoelcampos/cloudsim-plus#281]
## Actual behavior 
start running the simulation then this exception occurs "java.lang.outofmemoryerror thrown from the uncaughtexceptionhandler in thread "main" .
I tried increasing heap size but nothing was changed. 

## Expected behavior
complete the simulation as it is run correctly in version 5.4.3

## If it is a wider problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
 
```
simulation=new CloudSim();	
    createDatacenter();
    createCloudletsAndBrokersFromTraceFile(Task_events);
    brokers.forEach(broker -> broker.submitVmList(createVms()));
    simulation.start();
```

## Specifications like the version of the project, operating system or workload file used
I read task events file from google cluster dataset v2, my example is similar to GoogleTaskEventsExample class 
I am using eclipse  version 2020-06

**Comment by manoelcampos** [comment]
The issue probably is not with CloudSim Plus. It has already happened in previous versions?
Google traces are huge, and that explains why you are getting OutOfMemoryError.

The execution of the applications may required the increase in the Java Heap Size using the `-Xmx` JVM command line parameter. For instance, use `-Xmx5G` for 5GB or heap space.
Please try that and let me know how it goes.

**Comment by manoelcampos** [comment]
Make sure you are using the latest version from GitHub.

**Comment by Doaa-h** [comment]
I increased heap size in run configuration to 4G and 5G but the problem did not solve.
this problem just happens with v6 when I use task events files even it is sample file (small size data)!
Is there any computer specification required with CloudSim Plus v6? I have windows 8.1 with 8G RAM

**Comment by manoelcampos** [comment]
There are no specific hardware requirements to run CloudSim Plus. Could you please attach the simulation scenario you are running?

**Comment by Doaa-h** [comment]
[GoogleTaskEventsExample2.txt](https://github.com/manoelcampos/cloudsim-plus/files/5986701/GoogleTaskEventsExample2.txt)

**Comment by manoelcampos** [comment]
Hey @Doaa-h 
Sorry for the really late reply. I've been very busy with my PhD and it's being hard to maintain the framework practically alone. Furthermore, this issue was tricky. It turns out that was a long-living issue inherited from CloudSim event creation and future event queue management.
Now it's fixed. Check the commit message for details.

**Comment by manoelcampos** [comment]
Some cloudlet finish messages were being missed, making the simulation go in infinite loop.
