### ISSUE TITLE
How can I simulate running a Real Java Task as cloudlet 

### ISSUE THREAD

**Issue by RahulParmarRP** [manoelcampos/cloudsim-plus#293]
I need help for my project, I need to simulate, load balancing using Firefly and Particle Swarm Algorithms, and above that, I need to perform the tasks, when the user uploads the file on the server, I need to check the files using File level Data Deduplication. 

So basically what I wanted to know is like can we host a real virtual server as a VM to perform tasks, or can I simulate running the **Java Threads/Tasks** as the **cloudlets** in the simulation, so that I can also check the load balancing scenario using those tasks.
Thanks.

**Comment by manoelcampos** [comment]
Please subscribe to the forum to get this kind of help. Make sure you provide all the info requested or your application you'll be summarily rejected.
