### ISSUE TITLE
VM vertical scaling

### ISSUE THREAD

**Issue by manoelcampos** [manoelcampos/cloudsim-plus#7]
# Feature
Implement a mechanism for scaling up and down VM resources during simulation execution.

## Detailed information about how the feature should work
The VM should have a property to enable vertical scaling and other ones to define minimal and maximum scaling capacity for each different resources (RAM, CPU and BW).

However, this can be tricky in real cloud environments, once both hypervisor  and guest operating systems may have to support hot adding resources such as RAM and CPU. For instance, it is reported that KVM and Microsoft Hyper-V supports such a feature. 
It has been reported that the OS has to provide such a "ballon driver" to allow hot addition of memory and CPU (without requiring bot reboot the VM).

## Concerns
There are two different ways to vertically scale a resource, by: 

1. **adding another virtual device for a VM** - for instance, to vertically scale the RAM, a new virtual memory card can be attached to the VM. A new CPU core can be attached as well. This is like performing a horizontal scaling at the resource level (since more CPUs will be made available).
2. **resizing the current resource** - the current capacity of a resource such as RAM can be dynamically resized. The VM will continue to have the same number of virtual devices (such as virtual memory cards), but with a different capacity. However, doing the same for CPU may not be possible in actual hypervisors. Thus, the better approach for CPU could be the first one. This is like performing a vertical scaling at the resource level (since the capacity of existing CPUs will be just resized up or down).

The implementation of this feature must consider how these different scaling mechanisms will be defined for each distinct resource such as RAM, BW, Storage and CPU. 

### Some issues to discuss

- How to define which kind of scaling a resource supports? 
- Will each resource accept just one kind of scaling or will it be allowed to support more than one?
- For RAM, BW and Storage resources, CloudSim Plus doesn't support adding more of such virtual devices to a VM (to simulate multiples memory cards, network cards or disks). It is just possible to add more CPUs (PEs). Adding such a support may not bring real benefits for simulation and may require a huge amount of changes. For simulation purposes, it doesn't matter if a VM has 1 or 2 virtual memory cards. It just matters the total amount of available RAM and other resources. The only special case is the CPUs, since more cores enables more Cloudlets to run simultaneously.

## References
- https://cwiki.apache.org/confluence/display/CLOUDSTACK/Dynamic+scaling+of+CPU+and+RAM
- http://www.unixarena.com/2015/12/linux-kvm-how-to-add-remove-vcpu-to-guest-on-fly.html
- http://www.linux-kvm.org/page/Projects/auto-ballooning
- https://labs.vmware.com/vmtj/memory-overcommitment-in-the-esx-server
- [VMware ESX CPU Hot-Plug](https://pubs.vmware.com/vsphere-4-esx-vcenter/index.jsp?topic=/com.vmware.vsphere.vmadmin.doc_41/vsp_vm_guide/configuring_virtual_machines/t_change_cpu_hotplug_settings.html)

## An example scenario where this feature should be used
- When a VM requires more resources and there are enough resources into the PM that can be assigned to the VM, in order to VM migration.
- When a VM is requiring more resources and the PM doesn't have enough ones, but other  co-hosted VM is not using all allocated resources and would lend it to the requesting VM.
## A brief explanation of why you think this feature is useful

It allows physical resources to be used in a more granular and efficient way, reducing resource wastage and VM migrations.

## Included Examples
- [VerticalVmRamScalingExample](https://github.com/manoelcampos/cloudsim-plus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/VerticalVmRamScalingExample.java)
- [VerticalVmCpuScalingExample](https://github.com/manoelcampos/cloudsim-plus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/VerticalVmCpuScalingExample.java)

**Comment by giovannifs** [comment]
Hi @manoelcampos, 

Are you working on this feature? Are you thinking to also implement vertical scaling for hosts?

Cheers,

**Comment by manoelcampos** [comment]
Hello @giovannifs,
I'm currently entirely re-engineering the network module that clearly was designed just to produce the results shown in the paper where it was presented (NetworkCloudSim paper).
It is not possible to use this module without performing changes in the source code. There are a lot of hardcoded parameters and the code is not totally reusable.

This is my to priority. I'm to work on that in this week. After that, I will analyse the next feature to work on.

I don't know exactly how the host vertical scaling is expected to work. You can open a new issue to request this feature. The issue form provide you information on how to request a new feature.

**Comment by manoelcampos** [comment]
Hello @giovannifs 

The last commit closed this issue, but it is currently just performing up scaling and needs more tests.
I will continue to work on that this week and it would be great if you could evaluate that and give some feedback.

Horizontal VM Scaling already was implemented. See issue #41 

Thank you.

**Comment by manoelcampos** [comment]
Vertical down scaling is being implemented.

**Comment by manoelcampos** [comment]
There are two different kinds of vertically scaling a resource: 

1. **by adding another virtual device for a VM**: For instance, to scale the RAM vertically, a new virtual memory card can be attached to the VM. A new CPU core can be attached as well.
2. **by resizing the current resource**: the current capacity of a resource such as RAM can be dynamically resized. The VM will continue to have the same number of virtual memory cards, but with a different capacity. However, doing the same for CPU may not be possible in actual hypervisors. Thus, the better approach for CPU could be the first one.

**Comment by manoelcampos** [comment]
Hello @giovannifs,
I don't know if you have seen my message, but this feature is already working and under tests.
You can check a [discussion here](https://groups.google.com/forum/#!topic/cloudsim-plus/Yogx3ENvUYU).

**Comment by Jolanare** [comment]
i want to implement kmeans to minimize sla violation but i couldn't run  this can you help me

**Comment by manoelcampos** [comment]
@Jolanare subscribe to the forum to get support.

**Comment by Jolanare** [comment]
hello again Sir

**Comment by Jolanare** [comment]
Well no one can help me :/
